apps/kubernetes-dashboard/clusterrolebinding.yaml
apps/kubernetes-dashboard/helm-release.yaml
apps/kubernetes-dashboard/helm-repository.yaml
apps/kubernetes-dashboard/kustomization.yaml
apps/kubernetes-dashboard/namespace.yaml
apps/kubernetes-dashboard/serviceaccount.yaml

I would like to enable people to view the state of our Kubernetes anonymously with this

:sparkles: add Kubernetes dashboard

---

apps/kustomization.yaml

actually, I forgot to add the entry in the last PR ;)

release kubernetes dashboard

---

apps/grafana/dashboards.yaml
apps/grafana/datasource.yaml
apps/grafana/helm-release.yaml
apps/grafana/helm-repository.yaml
apps/grafana/kustomization.yaml
apps/grafana/namespace.yaml
apps/kustomization.yaml

This adds Grafana app for dashboards
ToDo:

:sparkles: Add Grafana app

---

apps/prometheus/helm-release.yaml

- increase replica count to 3
- set retention to 14 days
- provision a volume from local path

:wrench: Configure Prometheus

---

apps/kustomization.yaml
apps/labello/deployment.yaml
apps/labello/ingress.yaml
apps/labello/kustomization.yaml
apps/labello/namespace.yaml
apps/labello/service.yaml

This is a port of https://github.com/chaosdorf/docker-stacks/blob/main/enabled/labello.yml.
It would be nice to add the SENTRY_DSN secret.

:sparkles: Add app labello

---

apps/kustomization.yaml
apps/snapcast-server/helm-release.yaml
apps/snapcast-server/helm-repository.yaml
apps/snapcast-server/kustomization.yaml
apps/snapcast-server/namespace.yaml

PR installs a Snapcast server Helm chart.
> Snapcast is a multi-room client-server audio player, where all clients are time synchronized with the server to play perfectly synced audio. It’s not a standalone player, but an extension that turns your existing audio player into a Sonos-like multi-room solution.

Install Snapcast Server Helm Chart 🎶

---

apps/heimdall/helm-release.yaml
apps/heimdall/helm-repository.yaml
apps/heimdall/kustomization.yaml
apps/heimdall/namespace.yaml
apps/kustomization.yaml

PR installs Heimdall as a link dashboard into the cluster.

Add Heimdall Dashboard

---

apps/jellyfin/helm-release.yaml
apps/jellyfin/helm-repository.yaml
apps/jellyfin/kustomization.yaml
apps/jellyfin/namespace.yaml
apps/kustomization.yaml

Install Jellyfin 🎥

---

apps/jellyfin/helm-release.yaml

📀 Extend Jellyfin PVC

---

apps/ersatztv/helm-release.yaml
apps/ersatztv/helm-repository.yaml
apps/ersatztv/kustomization.yaml
apps/ersatztv/namespace.yaml
apps/kustomization.yaml

PR installs [ErsatzTV](https://github.com/ErsatzTV/ErsatzTV) into the cluster to set up our own Chaosdorf TV station! 📡📺

Install ErsatzTV 📺

---

apps/ariang/helm-release.yaml
apps/ariang/helm-repository.yaml
apps/ariang/kustomization.yaml
apps/ariang/namespace.yaml
apps/kustomization.yaml

PR installs the AriaNg download manager.

Install AriaNg 🛜

---

apps/ariang/helm-release.yaml

Fix AriaNg Deployment

---

apps/prometheus/helm-release.yaml

enable internal Prometheus ingress for hackcenter dashboard

enable ingress for prometheus

---

apps/beamerstreamer/endpoints.yaml
apps/beamerstreamer/ingress.yaml
apps/beamerstreamer/kustomization.yaml
apps/beamerstreamer/namespace.yaml
apps/beamerstreamer/service.yaml

PR adds ingress for the beamer streamer host.

Add Beamer Streamer Ingress

---

apps/copyparty/helm-release.yaml

PR updates the command for copyparty to allow modification access

Fix CopyParty NFS Access

---

apps/jellyfin/helm-release.yaml

PR passes through the entire iGPU to Jellyfin.

Fix Jellyfin Hardware Transcoding

---

apps/kustomization.yaml
apps/registry/helm-release.yaml
apps/registry/helm-repository.yaml
apps/registry/kustomization.yaml
apps/registry/namespace.yaml

PR installs a container image registry we can use for our own container images.

Install Container Image Registry

---

apps/inventory/deployment.yaml
apps/inventory/ingress.yaml
apps/inventory/kustomization.yaml
apps/inventory/namespace.yaml
apps/inventory/service.yaml
apps/inventory/volumes.yaml
apps/kustomization.yaml

PR installs https://git.aachen.ccc.de/inventory/in into the cluster.

Installing Inventory App

---

apps/vault/values.yaml

Configure Vault for high-availability with 3 instances, using integrated
Raft storage.

feat: Enable Vault high-availability

---

.github/workflows/christian-linter.yaml

Add linting

---

apps/kyverno/enforce-replica.yaml
apps/kyverno/kustomization.yaml
infra/kustomization.yaml
infra/kyverno/helm-release.yaml
infra/kyverno/helm-repository.yaml
infra/kyverno/kustomization.yaml
infra/kyverno/namespace.yaml

With Kyverno, we can apply policies to our cluster. With this change, we
introduce a policy that changes all deployments to show 3 replicas.

feat: Add app Kyverno

---

apps/copyparty/helm-release.yaml

chore: update copyparty to v1.19.0
